"""
train_policy_models.py

This script trains one machine learning model per product to predict the
best restock quantity.

High-level workflow:
1. Load the simulation dataset and configuration files.
2. Reconstruct the simulation state for each day from the logged dataset.
3. For each product and each day, evaluate several candidate restock quantities
   by replaying a short simulation rollout.
4. Label each row with the best-performing restock quantity.
5. Train a Random Forest classifier for each product separately.
6. Save the trained models, labeled training tables, and feature importances.

The goal is to learn a restocking policy that balances:
- profit / reward
- waste / scrapped inventory
- unmet demand
"""

import json
import os
from dataclasses import dataclass
from typing import Dict, List, Tuple

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split

from managers import (
    CustomerManager,
    InventoryManager,
    ScenarioGeneratorRandom,
    StatManager,
    SupplyManager,
)
from envs import DailySimulation


# ---------------------------------------------------------------------
# File paths and training settings
# ---------------------------------------------------------------------

# Input dataset generated by the simulation.
DATASET_PATH = "./simulation_dataset.csv"

# Configuration files used to rebuild the simulation components.
PROD_CONFIG_PATH = "./configurations/conf_Products.json"
STORE_CONFIG_PATH = "./configurations/conf_Store.json"

# Folder where all trained artifacts will be stored.
MODEL_DIR = "./trained_models"

# We score candidate quantities using:
#   score = reward - LAMBDA_SCRAP * scrapped - LAMBDA_UNMET * unmet
#
# Increasing LAMBDA_SCRAP makes the labeler care more about waste.
# Increasing LAMBDA_UNMET makes the labeler care more about stockouts.
LAMBDA_SCRAP = 2.0
LAMBDA_UNMET = 1.0

# Number of Monte Carlo rollouts used when evaluating each candidate quantity.
# Larger values reduce noise but increase runtime.
N_ROLLOUTS = 3

# Fraction of rows held out for model evaluation.
TEST_SIZE = 0.25

# Random seed used for reproducibility in train/test split and model training.
RANDOM_STATE = 42


# ---------------------------------------------------------------------
# Data structure used to represent one reconstructed day of simulation
# ---------------------------------------------------------------------

@dataclass
class DayState:
    """
    Compact representation of the simulation state for one day.

    Attributes:
        day_idx:
            Absolute day number in the dataset.

        weekday:
            Day of week, typically 0-6.

        baseline_actions:
            Original restock quantities used in the logged dataset for this day,
            stored as {product_name: quantity}.

        inventory:
            Inventory arrays for each product at the start of the day,
            stored as {product_name: np.ndarray}.

        pipeline:
            On-order / in-transit arrays for each product at the start of the day,
            stored as {product_name: np.ndarray}.

        todays_demand:
            Reconstructed total demand for that day.
    """
    day_idx: int
    weekday: int
    baseline_actions: Dict[str, int]
    inventory: Dict[str, np.ndarray]
    pipeline: Dict[str, np.ndarray]
    todays_demand: int


# ---------------------------------------------------------------------
# Basic utility helpers
# ---------------------------------------------------------------------

def load_json(path: str) -> dict:
    """Load and return a JSON file as a Python dictionary."""
    with open(path, "r") as f:
        return json.load(f)


def ensure_dir(path: str) -> None:
    """Create a directory if it does not already exist."""
    os.makedirs(path, exist_ok=True)


# ---------------------------------------------------------------------
# Simulation reconstruction helpers
# ---------------------------------------------------------------------

def build_consumer(prod_setting: dict, store_setting: dict) -> CustomerManager:
    """
    Build the customer choice model from the configuration files.

    The consumer model expects one flat list of prices and one flat list of
    qualities covering every product-age combination.
    """
    consumer = CustomerManager(store_setting["DCM"])

    prices = []
    qualities = []

    for product_name in prod_setting.keys():
        prices.extend(prod_setting[product_name]["P"])
        qualities.extend(prod_setting[product_name]["Q"])

    consumer.setPrices(np.array(prices))
    consumer.setQuality(np.array(qualities))

    return consumer


def build_env_from_state(
    prod_setting: dict,
    store_setting: dict,
    state: DayState,
    seed: int,
) -> DailySimulation:
    """
    Rebuild a fresh simulation environment from a stored DayState.

    Take a logged state from the dataset, rebuild the environment from it,
    and then test alternative restock quantities from that same starting point.

    We use a short 7-day horizon because the original simulator is weekly-based.
    """
    scenarioMgr = ScenarioGeneratorRandom(store_setting)
    scenarioMgr.setSeed(seed)

    invManagers = {
        product_name: InventoryManager(prod_setting[product_name]["SL"])
        for product_name in prod_setting.keys()
    }

    supManagers = {
        product_name: SupplyManager(prod_setting[product_name]["LT"])
        for product_name in prod_setting.keys()
    }

    statMgr = StatManager(prod_setting)
    statMgr.setHeadTail(0, 0)

    consumer = build_consumer(prod_setting, store_setting)

    env = DailySimulation(
        scenarioMgr=scenarioMgr,
        timeHorizon=7,
        invManagers=invManagers,
        supManagers=supManagers,
        statMgr=statMgr,
        consumer=consumer,
        flagPrint=False,
    )

    # Inject the saved state directly into the environment.
    # We do not call reset(), because reset would wipe these values.
    for product_name in prod_setting.keys():
        env.invManagers[product_name].inventory = state.inventory[product_name].astype(int).copy()
        env.supManagers[product_name].OnOrder = state.pipeline[product_name].astype(int).copy()

    env.current_step = 0

    # Create a short scenario array. The first day is populated immediately,
    # and the caller may overwrite future days for rollout evaluation.
    env.scenario = np.zeros((1, 7))
    env.scenario[0, 0] = state.todays_demand

    # Clear simulation bookkeeping so the rollout starts cleanly.
    env.history = {product_name: [] for product_name in prod_setting.keys()}
    env.sales = {
        product_name: np.zeros(env.invManagers[product_name].shelfLife)
        for product_name in prod_setting.keys()
    }
    env.dataset_rows = []

    env.statMgr.clearStatistics()
    env.statMgr.setTimeHorizon(7)

    return env


def infer_day_states(df: pd.DataFrame, prod_setting: dict) -> List[DayState]:
    """
    Reconstruct one DayState per day from the logged simulation dataset.

    The dataset stores one row per product per day, so this function groups rows
    by day_idx and rebuilds the full multi-product state for that day.

    This function also handles products with different shelf lives and lead times.
    """
    required_products = set(prod_setting.keys())
    day_states: List[DayState] = []

    for day_idx, day_df in df.groupby("day_idx"):
        products_present = set(day_df["product"].unique())

        # Skip incomplete days that do not contain all configured products.
        if products_present != required_products:
            continue

        inventory = {}
        pipeline = {}
        baseline_actions = {}

        for _, row in day_df.iterrows():
            product = row["product"]

            sl = int(prod_setting[product]["SL"])
            lt = int(prod_setting[product]["LT"])

            # Only read the slot columns that actually belong to this product.
            inv_cols = [f"inv_age_slot_{i}" for i in range(sl)]
            pipe_cols = [f"pipeline_slot_{i}" for i in range(lt + 1)]

            inventory[product] = (
                row.reindex(inv_cols)
                .fillna(0)
                .to_numpy(dtype=int)
            )

            pipeline[product] = (
                row.reindex(pipe_cols)
                .fillna(0)
                .to_numpy(dtype=int)
            )

            baseline_actions[product] = int(round(float(row["action_ordered"])))

        # lost_clients and unmet_clients are repeated on each product row,
        # so max() recovers the day's value.
        total_sold = int(day_df["total_sold"].sum())
        lost_clients = int(day_df["lost_clients"].max())
        unmet_clients = int(day_df["unmet_clients"].max())

        # Reconstruct total demand as:
        # demand = sold + lost + unmet
        todays_demand = total_sold + lost_clients + unmet_clients
        weekday = int(day_df["weekday"].iloc[0])

        day_states.append(
            DayState(
                day_idx=int(day_idx),
                weekday=weekday,
                baseline_actions=baseline_actions,
                inventory=inventory,
                pipeline=pipeline,
                todays_demand=todays_demand,
            )
        )

    return sorted(day_states, key=lambda s: s.day_idx)


# ---------------------------------------------------------------------
# Candidate restock quantity search
# ---------------------------------------------------------------------

def build_candidate_actions_for_product(product: str) -> List[int]:
    """
    Return the allowed restock quantities for a given product.

    These are the classes the model will predict.
    """
    if product == "A":
        return [0, 80, 140, 200, 280]
    elif product == "B":
        return [0, 60, 100, 150, 200]
    else:
        raise ValueError(f"Unknown product: {product}")


def evaluate_candidate_action(
    product: str,
    candidate_action: int,
    state: DayState,
    prod_setting: dict,
    store_setting: dict,
    lambda_scrap: float,
    n_rollouts: int,
    rollout_days: int = 5,
    lambda_unmet: float = 1.0,
) -> float:
    """
    Evaluate one candidate restock quantity using short Monte Carlo rollouts.

    Logic:
    - Rebuild the environment from a logged state.
    - On day 0, change only the target product's quantity to the candidate value.
    - Keep all other products at their baseline quantities.
    - For later rollout days, use baseline quantities for all products.
    - Compute an average score across multiple stochastic rollouts.

    Returns:
        Mean rollout score for the candidate quantity.
    """
    scores = []
    product_names = list(prod_setting.keys())

    for rollout in range(n_rollouts):
        env = build_env_from_state(
            prod_setting=prod_setting,
            store_setting=store_setting,
            state=state,
            seed=1000 + state.day_idx * 97 + rollout,
        )

        total_score = 0.0

        # Build a simple future demand scenario.
        # For now, repeat today's demand for each rollout day.
        env.scenario = np.zeros((1, env.timeHorizon))
        for day_offset in range(min(rollout_days, env.timeHorizon)):
            env.scenario[0, day_offset] = state.todays_demand

        for day_offset in range(rollout_days):
            if day_offset == 0:
                # On the first day, change only the target product.
                action = np.array(
                    [
                        candidate_action if product_name == product else state.baseline_actions[product_name]
                        for product_name in product_names
                    ],
                    dtype=float,
                )
            else:
                # On later days, follow the baseline policy.
                action = np.array(
                    [state.baseline_actions[product_name] for product_name in product_names],
                    dtype=float,
                )

            _, reward, done, _ = env.step(action)

            # Read the environment's logged rows to compute penalties.
            step_df = env.get_dataset()
            day_df = step_df[step_df["day_idx"] == day_offset]

            total_scrapped = float(day_df["scrapped"].sum()) if not day_df.empty else 0.0
            total_unmet = float(day_df["unmet_clients"].max()) if not day_df.empty else 0.0

            day_score = (
                float(reward)
                - lambda_scrap * total_scrapped
                - lambda_unmet * total_unmet
            )

            total_score += day_score

            if done:
                break

        scores.append(total_score)

    return float(np.mean(scores))


def choose_best_restock_qty(
    product: str,
    candidate_actions: List[int],
    state: DayState,
    prod_setting: dict,
    store_setting: dict,
) -> Tuple[int, float]:
    """
    Evaluate all candidate quantities and return the best one.
    """
    best_qty = candidate_actions[0]
    best_score = -np.inf

    for qty in candidate_actions:
        score = evaluate_candidate_action(
            product=product,
            candidate_action=qty,
            state=state,
            prod_setting=prod_setting,
            store_setting=store_setting,
            lambda_scrap=LAMBDA_SCRAP,
            n_rollouts=N_ROLLOUTS,
            rollout_days=5,
            lambda_unmet=LAMBDA_UNMET,
        )

        if score > best_score:
            best_score = score
            best_qty = qty

    return best_qty, best_score


# ---------------------------------------------------------------------
# Feature engineering
# ---------------------------------------------------------------------

def engineer_features(row: pd.Series, product: str, prod_setting: dict) -> dict:
    """
    Convert one logged product-day row into model features.

    Features include:
    - time features
    - inventory summary features
    - pipeline summary features
    - raw inventory/pipeline slots
    - demand-related observations
    """
    sl = int(prod_setting[product]["SL"])
    lt = int(prod_setting[product]["LT"])

    inv_cols = [f"inv_age_slot_{i}" for i in range(sl)]
    pipe_cols = [f"pipeline_slot_{i}" for i in range(lt + 1)]

    inv = row.reindex(inv_cols).fillna(0).to_numpy(dtype=float)
    pipe = row.reindex(pipe_cols).fillna(0).to_numpy(dtype=float)

    features = {
        "weekday": float(row["weekday"]),
        "total_inventory": float(inv.sum()),
        "expiring_soon": float(inv[0]) if inv.size > 0 else 0.0,
        "fresh_inventory": float(inv[-1]) if inv.size > 0 else 0.0,
        "inventory_mean_age_pressure": float(np.dot(np.arange(inv.size), inv)) if inv.size > 0 else 0.0,
        "total_pipeline": float(pipe.sum()),
        "arriving_today": float(pipe[0]) if pipe.size > 0 else 0.0,
        "arriving_later": float(pipe[1:].sum()) if pipe.size > 1 else 0.0,
        "lost_clients": float(row["lost_clients"]),
        "unmet_clients": float(row["unmet_clients"]),
    }

    # Include raw slot values as features too, so the model can learn
    # more detailed age- and lead-time-specific patterns.
    for col_name, value in zip(inv_cols, inv):
        features[col_name] = float(value)

    for col_name, value in zip(pipe_cols, pipe):
        features[col_name] = float(value)

    return features


# ---------------------------------------------------------------------
# Training table construction
# ---------------------------------------------------------------------

def build_training_tables(
    df: pd.DataFrame,
    prod_setting: dict,
    store_setting: dict,
) -> Dict[str, pd.DataFrame]:
    """
    Build one labeled training table per product.

    Each row is turned into:
    - input features describing the state
    - a label = best_restock_qty, found by rollout evaluation
    """
    day_states = infer_day_states(df, prod_setting)
    training_tables = {}

    for product in prod_setting.keys():
        print(f"\nBuilding restock labels for product {product}...")

        df_product = df[df["product"] == product].copy()
        df_product = df_product.sort_values("day_idx").reset_index(drop=True)

        candidate_actions = build_candidate_actions_for_product(product)
        print(f"Candidate restock quantities for {product}: {candidate_actions}")

        rows = []
        state_map = {state.day_idx: state for state in day_states}

        for _, row in df_product.iterrows():
            day_idx = int(row["day_idx"])

            if day_idx not in state_map:
                continue

            state = state_map[day_idx]

            best_qty, best_score = choose_best_restock_qty(
                product=product,
                candidate_actions=candidate_actions,
                state=state,
                prod_setting=prod_setting,
                store_setting=store_setting,
            )

            feature_row = engineer_features(row, product, prod_setting)
            feature_row["best_restock_qty"] = int(best_qty)
            feature_row["best_score"] = float(best_score)
            rows.append(feature_row)

        training_tables[product] = pd.DataFrame(rows)

    return training_tables


# ---------------------------------------------------------------------
# Model training and saving
# ---------------------------------------------------------------------

def train_and_save_model(product: str, train_df: pd.DataFrame) -> None:
    """
    Train one Random Forest model for one product, then save:
    - the model
    - the labeled training table
    - the feature importance table
    """
    if train_df.empty:
        print(f"No training data for product {product}. Skipping.")
        return

    # Remove classes that are too rare to train reliably.
    min_count = 20
    counts = train_df["best_restock_qty"].value_counts()
    valid_classes = counts[counts >= min_count].index

    print(f"\nFiltering rare classes for {product}...")
    print("Before:", counts.to_dict())

    train_df = train_df[train_df["best_restock_qty"].isin(valid_classes)]

    counts_after = train_df["best_restock_qty"].value_counts()
    print("After:", counts_after.to_dict())

    # Guard against accidental empty or single-class training sets.
    if train_df.empty:
        print(f"No data left for product {product} after filtering. Skipping.")
        return

    if train_df["best_restock_qty"].nunique() < 2:
        print(f"Not enough class diversity for product {product} after filtering. Skipping.")
        return

    X = train_df.drop(columns=["best_restock_qty", "best_score"])
    y = train_df["best_restock_qty"].astype(int)

    # Stratify the split when possible so class proportions stay more stable.
    stratify_arg = y if y.nunique() > 1 else None

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=TEST_SIZE,
        random_state=RANDOM_STATE,
        stratify=stratify_arg,
    )

    model = RandomForestClassifier(
        n_estimators=300,
        max_depth=10,
        min_samples_leaf=3,
        class_weight="balanced",
        random_state=RANDOM_STATE,
        n_jobs=-1,
    )

    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    print(f"\n=== Product {product} Restock Quantity Model ===")
    print(f"Accuracy: {accuracy_score(y_test, y_pred):.4f}")
    print(classification_report(y_test, y_pred, zero_division=0))

    artifact = {
        "model": model,
        "feature_columns": X.columns.tolist(),
        "product": product,
        "target_name": "best_restock_qty",
    }

    model_path = os.path.join(MODEL_DIR, f"rf_restock_qty_{product}.joblib")
    joblib.dump(artifact, model_path)
    print(f"Saved model to: {model_path}")

    train_csv = os.path.join(MODEL_DIR, f"training_table_{product}.csv")
    train_df.to_csv(train_csv, index=False)
    print(f"Saved training table to: {train_csv}")

    importances = pd.DataFrame({
        "feature": X.columns,
        "importance": model.feature_importances_,
    }).sort_values("importance", ascending=False)

    imp_csv = os.path.join(MODEL_DIR, f"feature_importance_{product}.csv")
    importances.to_csv(imp_csv, index=False)
    print(f"Saved feature importances to: {imp_csv}")


# ---------------------------------------------------------------------
# Main script entry point
# ---------------------------------------------------------------------

def main():
    """Load data, build labels, train product-specific models, and save outputs."""
    ensure_dir(MODEL_DIR)

    prod_setting = load_json(PROD_CONFIG_PATH)
    store_setting = load_json(STORE_CONFIG_PATH)

    df = pd.read_csv(DATASET_PATH)
    if df.empty:
        raise ValueError("The dataset is empty.")

    expected_products = set(prod_setting.keys())
    found_products = set(df["product"].unique())
    missing = expected_products - found_products

    if missing:
        raise ValueError(f"Dataset missing products: {missing}")

    training_tables = build_training_tables(df, prod_setting, store_setting)

    for product, train_df in training_tables.items():
        train_and_save_model(product, train_df)

    print("\nDone.")


if __name__ == "__main__":
    main()